#+TITLE: The Search for a Runtime Host

How does one decide in which language to implement a language? Familiarity with
a language is the default criterion since I want to focus on the implementand
and not worry about learning the implemention language.

But the scripting and jvm languages I'm most familiar might not be the most
suitable to task.

The problem with an approach like this is that I know myself and I'm not going
to put a lot of effort into alternate language implementations if I get one
working in clojure.

* Criteria
  Simple rubric by which to evaluate a language.
  Note that we're assuming here that I'll use the llvm as backend early on.
** Interactive development
   This
** Implement a lisp repl
   Any language can do this, but evaluate the simplicity of different solutions.
** C FFI
** Generate Vulkan bindings from vulkan.xml
** Suitability of host language as initial runtime
*** concurrency and message passing
*** sandboxing
*** ease of gradual bootstrapping
* Possible candidates
** Clojure
*** Interactive dev
    cidre
*** implement lisp repl
    trivial
*** C FFI
   JNI is a shitshow.
   This might do better: https://github.com/jnr/jnr-ffi

   Needs a thorough evaluation. Or just evaluate this guy's attempt and use some
   of his work:
   https://github.com/omkamra/jnr/blob/master/test/omkamra/jnr_test.clj
*** Generate vulkan bindings from xml
    clj-vulkan project is a basic proof of concept, but it needs to be ported to
    a better ffi than lwjgl uses.
*** Suitability as an initial runtime
    migrating off of the jvm might prove to be a mammoth undertaking. I have to
    remove all vestiges of java bytecode from the app which could take forever.

    The jvm is also heavy, so I'm not sure how interactive the experience will
    be as datastructures are translated back and forth.

    Is is possible to implement clojure protocols with native datatypes? If so,
    then once I migrate the data structures, everything will start to fall into
    place. Otherwise I'll need to get everything working before any of it will
    work. Or suffer interminable translation back and forth.

    On the otherhand, forcing a clean break might be a good thing. If I were to
    use Go, for instance, I might just leave the native channels in place
    indefinitely because they're there. Not sure that's a bad thing.
** Common Lisp
** Forth?
   Are there any remotely modern implementations? Some quick research makes it
   look like I'd be better off implementing my own.
** Go
** Julia
   Julia shares a lot of the spirit of what I'm doing. Dynamic and fast,
   heterogeneous, jit compiled, hosted, the AST is lisp (can I program in the
   ast without learning the surface syntax?) so we get real macros (though
   they're probably unnatural to most people learning julia from the blub world
   as it's marketed to data science and scientific computing, so fortran to python
   spectrum.).

   I almost feel that I have to implement this in julia just to learn about how
   the language is implemented.

   The number types were clearly thought out with mathematics in mind — and not
   just numerics — which is so rare for a programming language.
** Zig
** Nim
** Chapel
   Chapel is designed ground up for distributed programming which is one
   of the things I need. I don't know much about it, but it deserves a hearing.
* unicode
  Unicode is important. Not what I really want to focus on, but I need it.
  π ∀

* Test V1
  What's the simplest program that tests all the moving parts?

  Lisp repl that can interpret or jit compile functions and execute them.

  We don't need to implement the full compiler, just a big enough subset to get
  the idea.

  So
  - Basic Abstractions
    - conj/disj
    - get/nth
    - assoc/dissoc
    - count
    - sequences
      Sequences turn out to be surprisingly important.

      A sequence is just an abstraction that has (poosibly) a next thing and (possibly)
      more things. Sequences can be eager or lazy, they can be chunked, they can
      be async. So channels / streams are going to fall into the sequence
      abstraction just like the in memory collections.

      Also important: a seq doesn't have to fit in memory. Lazy seqs are an
      obvious way to do this, but distributed seqs are also seqs and allowing
      them to be chunked async should make it trivial to operate on them as if
      they were available locally (and manipulate them without ever fetching
      them locally).
  - data structures
    (just vectors and maps to start, copy on write is good enough for a demo).
  - reader
  - interpreter
  - Code internment and reference by value.
  - pretty print?
  - C FFI to llvm
  - bitcode generation
  - jit compile and replace interpreted fns with flubs.
** Julia
   - [X] reader
     I basically copied the clojure reader, dropping most of the
     functionality. But ~200 lines of code and a couple of days is pretty good
     considering I was both learing the language and the write a reader.

     This doesn't include the week long detour into the new control flow theory
     I developed.
   - [X] data structures
     Well, technically I have data structures. They're copy on write and maps
     are just alists, so don't count on performance. Sets are not implemented.
   - [ ] interpreter
     metacircular all the way. This is about clarity of semantics — as much as I
     hate that word — more than anything else. And the meaning of a program is
     indecipherable unless you can see what's happening inside the interpreter.
   - Resolution of names
     Is isn't something I had planned as part of the demo, but it's so important
     to later phases, that I'm thinking of taking a detour to try and bang out a
     very basic version of it.

     Copied from eval.jl comments:

     Here's a curious scenario: Where do we start with immutable names? I could
     resolve symbols right at first eval, but is that even soon enough? Maybe
     they should be resolved a read time.

     I think soething in between is actually what we want. Lambda's don't get
     evaled recursively when first read, but only when applied. But references
     should be fixed immediately...

     Possible workaround. Don't allow the user to define symbols at all. Have a
     special form `export`, `define`, etc. which takes a keyword and a form and
     interns a symbol pointing to the hash of the given form. This allows us to
     look up symbols at read time, so long as all forms referred to have been
     evalled beforehand.
   - [ ] pretty print?
     This will make life a lot easier if we do anything non-trivial.
* Test V2
  Once we have interop up and running:
  - Generate vulkan bindings from xml
  - write simple graphics program (fractal with pan and zoom should be complex
    enough to get a feel for fit).
  - Implement β and maybe μ.
